name: Claude Code

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  claude:
    # Only run when @claude is mentioned in comments or on new issues/PRs
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@claude')) ||
      (github.event_name == 'pull_request')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch full history for better context

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "client/package-lock.json"

      - name: Install dependencies
        run: |
          cd client
          npm ci

      - name: Run Claude Code
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          claude_args: |
            --max-turns 50
            --model claude-sonnet-4-20250514
          # Responds to @claude mentions in comments automatically

      - name: Auto-create PR for Claude branch
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          BASE_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          git fetch --all --prune
          BRANCH="$(git for-each-ref --sort=-committerdate --format='%(refname:short)' refs/remotes/origin/claude/* | head -n1 | sed 's#^origin/##')"
          if [ -z "$BRANCH" ]; then
            echo "No claude/* branch found. Skipping."
            exit 0
          fi

          # If a PR already exists for this branch, skip
          if gh pr view "$BRANCH" --json number >/dev/null 2>&1; then
            echo "PR already exists for $BRANCH. Skipping."
            exit 0
          fi

          TITLE="Claude: $(echo "$BRANCH" | sed 's#claude/##')"
          BODY="This PR was opened automatically after Claude pushed branch \`$BRANCH\`."

          gh pr create \
            --head "$BRANCH" \
            --base "${BASE_BRANCH:-main}" \
            --title "$TITLE" \
            --body "$BODY" \
            --draft=false
